spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username
                  - /api/short-link/admin/v1/user/send-forgot-password-email-code
                  - /api/short-link/admin/v1/user/forgot-password
                  - /api/short-link/admin/v1/user/send-register-email-code

        - id: short-link-project
          uri: lb://short-link-project
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/v1/stats/access-record/export
