server:
  port: 8002
spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis123
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  mail:
    host: smtp.qq.com
    port: 587
    username: ${EMAIL_USERNAME:1257180096@qq.com}
    password: ${EMAIL_PASSWORD:rjwreidpzcesjjjj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20

# MinIO配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: short-link-avatars

# 邮件配置

# 邮件发送配置
email:
  from: ${EMAIL_USERNAME:1257180096@qq.com}
  from-name: xDuo-短链接系统