server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      channel-topic:
        short-link-stats: 'short-link:stats-stream'
        short-link-stats-group: 'short-link:stats-stream:only-group'
      password: redis123
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      short-link-stats: short-link-stats
    consumer:
      group-id: short-link-stats-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10
    producer:
      acks: all
      retries: 3
      enable-idempotence: true
      max-in-flight-requests-per-connection: 1
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
short-link:
  stats:
    locale:
      amap-key: f4f8f283d183514f765a116f78ba2268
  domain:
    default: http://xDuo.top
  goto-domain:
    white-list:
      enable: false
      names: '知乎,掘金,博客园'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com

