# 数据源集合
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: d12345678

rules:
  - !SHARDING
    tables:
      t_link:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.t_link_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: gid
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: link_table_hash_mod
      t_link_goto:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.t_link_goto_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键 - 使用full_short_url，因为用户访问时只知道短链接
            shardingColumn: full_short_url
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: link_goto_table_hash_mod
      t_link_stats_today:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_0.t_link_stats_today_${0..15}
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: gid
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: link_stats_today_table_hash_mod
      t_link_access_logs:
        # 真实数据节点 - 扩展到64个分表
        actualDataNodes: ds_0.t_link_access_logs_${0..63}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_access_logs_table_hash_mod
      t_link_access_stats:
        # 真实数据节点 - 扩展到32个分表
        actualDataNodes: ds_0.t_link_access_stats_${0..31}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_access_stats_table_hash_mod
      t_link_browser_stats:
        # 真实数据节点
        actualDataNodes: ds_0.t_link_browser_stats_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_browser_stats_table_hash_mod
      t_link_device_stats:
        # 真实数据节点
        actualDataNodes: ds_0.t_link_device_stats_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_device_stats_table_hash_mod
      t_link_locale_stats:
        # 真实数据节点
        actualDataNodes: ds_0.t_link_locale_stats_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_locale_stats_table_hash_mod
      t_link_network_stats:
        # 真实数据节点
        actualDataNodes: ds_0.t_link_network_stats_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_network_stats_table_hash_mod
      t_link_os_stats:
        # 真实数据节点
        actualDataNodes: ds_0.t_link_os_stats_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_os_stats_table_hash_mod
      t_user:
        # 真实数据节点
        actualDataNodes: ds_0.t_user_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_table_hash_mod
      t_group:
        # 真实数据节点
        actualDataNodes: ds_0.t_group_${0..15}
        # 分表策略
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: group_table_hash_mod
      t_group_unique:
        # 真实数据节点 - 单表，不需要分片
        actualDataNodes: ds_0.t_group_unique
    bindingTables:
      - t_link, t_link_stats_today

    # 分片算法
    shardingAlgorithms:
      # 数据表分片算法
      link_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      link_goto_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      link_stats_today_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 16
      link_access_logs_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 64
      link_access_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 32
      link_browser_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_device_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      user_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      group_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_locale_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_network_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_os_stats_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
props:
  sql-show: true